### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by BLACK4585** [andrew-codes/playnite-web#621]
Hey,
it would be great if you could add a docker compose file, since I have some problems creating the MQTT broker.
Also this would made it easier to get the whole app up and running.

**Comment by BLACK4585** [comment]
Okay seems like I got it up and running now, a quick hint to the mosquitto.conf to disable local mode etc would be nice.
But somehow nothing is synced though.
However, a compose file would still be appreciated.

**Comment by kunla** [comment]
The docker-compose file below worked for me on Windows 10 using my WSL hostname as the <HOST> value.
```
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "0.0.0.0:1883:1883"
    volumes:
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    
  mongodb:
    image: mongo:focal
    ports:
      - "0.0.0.0:27017:27017"
    restart: unless-stopped
    
  playnite-web:
    image: ghcr.io/andrew-codes/playnite-web-app:10.1.0
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - PORT=3000
      - HOST=127.0.1.1
      - DB_HOST=mongodb
      - DB_PORT=27017
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    volumes:
      - playnite_assets:/opt/playnite-web-app/public/assets/asset-by-id
    depends_on:
      - mqtt
      - mongodb
    restart: unless-stopped

volumes:
  mqtt_data:
  mqtt_log:
  playnite_assets:
```

I also created a file named `mosquitto.conf` with the contents:
```
listener 1883 0.0.0.0
allow_anonymous true
```

Create a directory containing both files above and run `docker-compose up -d`
